attributes:
  metadata:
    restrictions:
      - condition: cluster:net_provider != 'neutron'
        message: "Please use neutron and/or uselect 'Use VLAN tagging' checkbox on Networks tab"
        action: disable
  segment_id_net1:
    value: ''
    label: 'VLAN id for default external network'
    description: 'VLAN id for Public network defined on "Networks" tab. You have to unselect "Use VLAN taggin" checkbox on "Networks" tab'
    weight: 25
    type: "text"
    regex:
      source: '^(409[0-4]|40[0-8][0-9]|[1-3][0-9]{3}|[1-9][0-9]{1,2}|[2-9])$'
      error: "VLAN id in range 2 - 4094"
  floating_subnet_net2:
    value: '10.6.132.0/22'
    label: 'Additional subnet'
    description: 'Subnet CIDR for additional net e.g. 10.6.132.0/22'
    weight: 30
    type: "text"
    regex:
      source: '^(?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3}(?:\/(?:[1-2]\d|[8-9]))$'
      error: "Invalid network CIDR"
  segment_id_net2:
    value: ''
    label: 'VLAN id for the additional external network'
    description: 'VLAN id for the additional external network'
    weight: 35
    type: "text"
    regex:
      source: '^(409[0-4]|40[0-8][0-9]|[1-3][0-9]{3}|[1-9][0-9]{1,2}|[2-9])$'
      error: "VLAN id in range 2 - 4094"
  floating_gateway_net2:
    value: '10.6.132.1'
    label: 'Router IP in additional net'
    description: 'IP addresss in additional network which will be assign to neutron router interface'
    weight: 40
    type: "text"
    regex:
      source: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
      error: "Specify valid IPv4 address"
  floating_range_net2:
    value: '10.6.132.100:10.6.132.200'
    label: 'Allocation pool in additional net'
    description: 'Range of addresses for IP allocations in additional net e.g. 10.6.132.100:10.6.132.200.'
    weight: 45
    type: "text"
    regex:
      source: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?):(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
      error: "Provide IP range in for of <ip>:<ip> e.g. 10.6.132.100:10.6.132.200"
